name: development

on:
  push:
    branches-ignore:
      - master
jobs:
  lint:
    name: lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.14.2'

      - name: Setup ENV
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"

      - name: Lint
        run: make lint

  dockerize:
    name: dockerize

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker
        uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: 1
          RUNNER_VERSION: 2.267.1
          DOCKER_VERSION: 19.03.8
        with:
          repository: aweris/gar
          build_args: RUNNER_VERSION=${{ env.RUNNER_VERSION }},DOCKER_VERSION=${{ env.DOCKER_VERSION }}
          add_git_labels: true
          tags: ${{ env.RUNNER_VERSION }}
          push: false