name: development

on:
  push:
    branches-ignore:
      - master
jobs:
  lint:
    name: lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.15'

      - name: Lint
        run: make lint

  dockerize:
    name: dockerize

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker
        uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: 1
          RUNNER_VERSION: 2.292.0
          DOCKER_VERSION: 20.10.16
        with:
          repository: aweris/gar
          build_args: RUNNER_VERSION=${{ env.RUNNER_VERSION }},DOCKER_VERSION=${{ env.DOCKER_VERSION }}
          add_git_labels: true
          tags: ${{ env.RUNNER_VERSION }}
          push: false
