name: release

on:
  push:
    branches:
      - master

jobs:
  dockerize:
    name: dockerize

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker
        uses: docker/build-push-action@v1
        env:
          DOCKER_BUILDKIT: 1
          RUNNER_VERSION: 2.273.2
          DOCKER_VERSION: 19.03.8
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: aweris/gar
          build_args: RUNNER_VERSION=${{ env.RUNNER_VERSION }},DOCKER_VERSION=${{ env.DOCKER_VERSION }}
          add_git_labels: true
          tags: ${{ env.RUNNER_VERSION }}
          push: true